# Generated by Django 5.0.1 on 2024-02-27 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField()),
                ('date_driven', models.DateTimeField()),
                ('fuel', models.CharField(choices=[('empty', 'Empty'), ('half', '1/2 Full'), ('three-quarters', '3/4 Full'), ('full', 'Full'), ('quarter', '1/4 Full')], max_length=15)),
                ('type', models.CharField(choices=[('out-bound', 'Out-bound'), ('in-bound', 'In-bound')], max_length=10)),
                ('engine_light_on', models.BooleanField(default=False)),
                ('noisy_brakes', models.BooleanField(default=False)),
                ('other_issues', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
